### ISSUE TITLE
Cannot Hide a progress dialog

### ISSUE THREAD

**Issue by atiqsamtia** [jzoom/sweetalert#3]
Can you please add an option to hide the progress dialog via programmatically! because in practice this is the need to have this option otherwise the progress dialog is not usable.

You can give a global Hide method or return the current instance from the Show method and give the option to perform the action on the instance.

**Comment by gigihiski** [comment]
I use `Navigator.of(context).pop();` for temporary solution.

**Comment by sathishmscict** [comment]
Hi @atiqsamtia  , using below code may be usefull for you to hide progress dialog : 
Navigator.pop(context);

**Comment by atiqsamtia** [comment]
@sathishmscict yes I did use this technique. Sorry forgot to close the issue.

Marking it Fixed now.! 

Thankyou

**Comment by sathishmscict** [comment]
> @sathishmscict yes I did use this technique. Sorry forgot to close the issue.
> 
> Marking it Fixed now.!
> 
> Thankyou

Your welcome
